# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:
title: Marc Ferrer Castillo
email: contact@marcferrer.eu
author: Marc Ferrer Castillo
description: > # "Write an awesome description for your new site here. 
  Personal github site from Marc Ferrer Castillo
copyright: 'Copyright &copy; 2022 Marc Ferrer Castillo. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 - title: email
    url: mailto:contact@marcferrer.eu
  - title: github
    url: https://github.com/Marc-Ferrer-Castillo
  - title: linkedin
    url: https://www.linkedin.com/in/marc-ferrer-castillo/
